### PR TITLE
Create `ru_ru.json`

### PR DESCRIPTION
**Pull request by mpustovoi**

### CODE REVIEW

**Comment by HiWord9** [comment]
Tbh, I can't tell for now would I or not like to accept it, but at least I can tell that lines 79-82 are not translated, should've done that

**Comment by mpustovoi** [comment]
Yes, indeed.

**Comment by mpustovoi** [comment]
Done.

**Comment by HiWord9** [comment]
So, i review the translation and i see a lot things i'd like to chage or even fix.
At leats, i noticed that some words are translated in a, let say, strange way, as:
- Stack
- configuration
- properties
- Reosurce pack name
- Mod name itself 
- compare

and some other. Also, i would change a form of some sentences.
I decided not to merge this rn, and i dont know will i or not. And if i will, i will also fix a lot of things by myself. And if i decide that this pr wont be accepted, i will close it, but for now im leaving it opened.

**Comment by mpustovoi** [comment]
> * Stack

In the [Minecraft official translation](https://crowdin.com/project/minecraft/ru), 'stack' is translated as 'стопка', not 'стак' or 'стэк'.

> * configuration

In `en_us.json` there was only one word 'config', which I translated as 'конфиг'. I can change it to its synonym 'настройки' (settings).

> * properties

In the Minecraft official translation, in 3/4 of the cases it's translated as 'свойства', and in other 1/4 it's 'параметры' (parameters).

> * Resource pack name

If you are talking about the translation of the single word 'pack', then (again, according to the official translation of the game) it's a 'набор' (which basically means 'set'). It's short for 'набор ресурсов' (resourcepack) or 'набор данных' (datapack). Honestly, I wouldn't translate it like that myself, and I'd prefer to leave the word 'пак' in Russian, but so far this word has not been added to the glossary.
If that's not what you're talking about, let me know.

> * Mod name itself

I agree here, this is a purely subjective point. I'll keep the original English name.

> * compare

Yes, I suppose here you meant it as 'match renames' rather than literally compare them with each other.

> Also, i would change a form of some sentences.

As for the sentences structure, I'm open to suggestions.

**Comment by HiWord9** [comment]
Congratulations! Thanks for ur contributuion!))

**Comment by HiWord9** [comment]
Good job
image
Before publishing the next version of mod i still need to change some things, as, at least, adding line breaks to tooltips on config screen and ofc this on screenshot.
Good translations anyway

**Comment by mpustovoi** [comment]
> Good job
> image

It's a shame that Mojang still hasn't implemented adaptive tooltips into the game.

I added line breaks in the same place as in `en_us.json`. And yet, the length of some sentences in Russian exceeds English.

**Comment by HiWord9** [comment]
> I added line breaks in the same place as in `en_us.json`. And yet, the length of some sentences in Russian exceeds English.

I see, some lines in engish are written in single line cause they are short in english, but in russian same text may take too much space and it needs breaks, like here:
image
meanwhile in english smae line is more than two time shorter:
image

just letting know

**Pull request merged**
